export const AGREGAR_PRODUCTO       = 'AGREGAR_PRODUCTO';
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO';
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR';

export const COMENZAR_DESCARGAR_PRODUCTOS = 'COMENZAR_DESCARGAR_PRODUCTOS';
export const DESCARGAR_PRODUCTO_EXITO = 'DESCARGAR_PRODUCTO_EXITO';
export const DESCARGAR_PRODUCTO_ERROR = 'DESCARGAR_PRODUCTO_ERROR';

